###############################################################################
#
# File: uploadFastQC.R
# Usage: Called/sourced by exframe_rtype.module; Process tab, Upload FastQC 
#   button, such as http://stemcellcommons.org/node/13293/rtype_process
#
# Purpose: This script will add the files generated by the FastQC
#   processing to the rtype_resultFiles table, so that these files can be 
#   displayed on the website.
#
################################################################################
# Copyright (C) 2013  Massachusetts General Hospital (MGH)
#
# This program is free software; you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation; either version 2 of the License, or (at your option) any later 
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
#
# You should have received a copy of the GNU General Public License along with 
# this program; if not, write to the Free Software Foundation, Inc. at 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Contact (mail): MIND Informatics
# 65 Landsdowne Street, Suite 200, Cambridge, MA 02139
# Contact (email): sudeshna.das2@gmail.com
#
###############################################################################

# Process command line arguments (XML and settings file)
exp_nid = commandArgs(TRUE)[1]
settings_file = commandArgs(TRUE)[2]
#exp_nid = 13293
#settings_file = "/var/www/sccr_project/secure/settings.txt"

# Load settings, reference files, global variables and connect to database
###############################################################################
# Read settings file 
data = read.table(settings_file, header=F)
dir_rlib = as.character(data[1,2])
dir_data = as.character(data[2,2])
dir_scripts = as.character(data[3,2])
database_user = as.character(data[4,2])
database_pass = as.character(data[5,2])
database_name = as.character(data[6,2])
database_host = as.character(data[7,2])
sparql_endpoint = as.character(data[8,2])
site_url = as.character(data[9,2])
alias_url = as.character(data[10,2])
RDF_reference_file = as.character(data[11,2])
isa_structure_file = as.character(data[12,2])
isa_translation_file = as.character(data[13,2])
ontology_reference_file = as.character(data[14,2])
drupal_path = as.character(data[15,2])
sparql_key = as.character(data[16,2])
server_path = as.character(data[17,2])

# Variables
method_name = "FastQC"
fastqc_folder_path = paste(dir_data, "/fastqc/", exp_nid, "/", sep = "")


if (file.exists(fastqc_folder_path)) {
  folder_list = list.files(fastqc_folder_path, pattern="_fastqc$")
  
  # Connect to database
  library(RMySQL, lib.loc=dir_rlib)
  m = dbDriver("MySQL")
  con = dbConnect(m, username=database_user, password=database_pass, dbname=database_name, host=database_host)
  rm(m)

  # Get job id
  rs <- dbSendQuery(con, paste("select job_id from rtype_jobs where exp_id = ", exp_nid, " AND job_type = 15 order by job_id desc", sep=""))
  job_id = fetch(rs, n=-1) #fetches all results
  job_id = job_id[1,1] #in case there is more than one job_id, choose most recent)
  
  # Get method id
  rs <- dbSendQuery(con, paste("SELECT method_id FROM rtype_methods WHERE name = '", method_name, "'", sep=""))
  method_id = fetch(rs, n=-1)
  method_id


} else {
  error_msg = paste("No FastQC directory exists for this experiment. The search path was", fastq_file_path,  "  Check that the FASTQC analysis has been run for experiment ", exp_nid, ".", sep = "")
  error_msg
  exit
}

for (j in seq(along=folder_list)) {
  file_type = "FASTQC"      # Specifies file type in the rtype_ResultFiles 
  file_path = paste(drupal_path, "/fastqc/", exp_nid, "/", folder_list[j],"/fastqc_report.html", sep = "")
  
  # Write FastQC file location to rtype_resultFiles
  rs <- dbSendQuery(con, paste("INSERT INTO rtype_resultFiles(job_id, file_path, file_type, method_id) VALUES(", job_id, ", '", file_path,"', '", file_type, "', ", method_id, ")", sep=""))
}

# Update job status
rs <- dbSendQuery(con, paste("UPDATE rtype_jobs SET status=1 WHERE job_id=", job_id, sep=""))


dbDisconnect(con)