###############################################################################
#
# File: uploadFastQC_input.R fastqc_files.csv
# Usage: Not yet determined
#
# Purpose: This script will add the files generated by fastqc into the
#  rtype_input table.
#
################################################################################
# Copyright (C) 2013  Massachusetts General Hospital (MGH)
#
# This program is free software; you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation; either version 2 of the License, or (at your option) any later 
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
#
# You should have received a copy of the GNU General Public License along with 
# this program; if not, write to the Free Software Foundation, Inc. at 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Contact (mail): MIND Informatics
# 65 Landsdowne Street, Suite 200, Cambridge, MA 02139
# Contact (email): sudeshna.das2@gmail.com
#
###############################################################################

# for testing
#input_path <- '/var/www/sccr_project/scripts/fastqc_files.csv'
#settings_file <- '/var/www/sccr_project/secure/settings.txt'

input_path <- commandArgs(TRUE)[1]
settings_file <- commandArgs(TRUE)[2]
fastqc_files <- read.delim(input_path, header=T, sep=",", as.is=T)
colnames(fastqc_files) <- c("rf_id", "job_id",	"exp_nid", "file")
fastqc_rows <- dim(fastqc_files)[1]




# Load settings, reference files, global variables and connect to database
###############################################################################
# Read settings file 
data = read.table(settings_file, header=F)
dir_rlib = as.character(data[1,2])
dir_data = as.character(data[2,2])
dir_scripts = as.character(data[3,2])
database_user = as.character(data[4,2])
database_pass = as.character(data[5,2])
database_name = as.character(data[6,2])
database_host = as.character(data[7,2])
sparql_endpoint = as.character(data[8,2])
site_url = as.character(data[9,2])
alias_url = as.character(data[10,2])
RDF_reference_file = as.character(data[11,2])
isa_structure_file = as.character(data[12,2])
isa_translation_file = as.character(data[13,2])
ontology_reference_file = as.character(data[14,2])
drupal_path = as.character(data[15,2])
sparql_key = as.character(data[16,2])
server_path = as.character(data[17,2])

# Global Variables
exp_nid <- 0
exp_replicates <- data.frame(nid = integer(0), fid = integer(0), filename = character(0), rep_id = integer(0))

  
# Connect to database
library(RMySQL, lib.loc=dir_rlib)
m = dbDriver("MySQL")
con = dbConnect(m, username=database_user, password=database_pass, dbname=database_name, host=database_host)
rm(m)
on.exit(dbDisconnect(con))

# for each row of the input data frame
for (j in 1:fastqc_rows) { 
  exp_line <- fastqc_files[j, "exp_nid"]
  job_id <- fastqc_files[j, "job_id"]
  rf_id <- fastqc_files[j, "rf_id"]
  
  if (exp_line != exp_nid) {  
    # Get replicates for this experiment so can match replicates to output files
    rs <- dbSendQuery(con, paste("select distinct node.nid, file_managed.fid, file_managed.filename, field_data_field_xf_replicate.field_xf_replicate_value as rep_id from file_managed left join field_data_field_xf_replicate_file ON file_managed.fid=field_data_field_xf_replicate_file.field_xf_replicate_file_fid left join field_data_field_xf_replicate on field_data_field_xf_replicate_file.entity_id = field_data_field_xf_replicate.field_xf_replicate_value left join field_data_field_xf_bioassay on field_data_field_xf_replicate.entity_id = field_data_field_xf_bioassay.field_xf_bioassay_target_id left join node on field_data_field_xf_bioassay.entity_id = node.nid where node.nid=", exp_line, sep=""))
    exp_replicates <- fetch(rs, n=-1)
    cat("Got experiment replicate ids...\n")
    exp_nid <- exp_line
  }
  
  # match the replicate file names to replicate ids
  replicate_file <- paste(fastqc_files[j, "file"], ".fastq.gz", sep="")
  rep_id <- exp_replicates[match(replicate_file, exp_replicates[,"filename"]), "rep_id"]
  
  cat("Line", j, "exp_nid: ", exp_nid, "   job_id:", job_id, "   replicate_id:", rep_id, "   rep_file:", replicate_file, "   fastqc_rf_id:", rf_id, "\n")
  
  # enter into rtype_input
  rs <- dbSendQuery(con, paste("INSERT INTO rtype_input(input_id, job_id, replicate_id, rf_id) VALUES(NULL, ", job_id, ", ", rep_id, ", ",rf_id, ")", sep=""))
}

