###############################################################################
#
# File: uploadDerivedFiles.R ChIP_DerivedFiles.csv
# Usage: Not yet determined
#
# Purpose: This script will add the files generated by analysis into the
#  rtype_resultFiles table.
#
################################################################################
# Copyright (C) 2013  Massachusetts General Hospital (MGH)
#
# This program is free software; you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation; either version 2 of the License, or (at your option) any later 
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
#
# You should have received a copy of the GNU General Public License along with 
# this program; if not, write to the Free Software Foundation, Inc. at 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Contact (mail): MIND Informatics
# 65 Landsdowne Street, Suite 200, Cambridge, MA 02139
# Contact (email): sudeshna.das2@gmail.com
#
###############################################################################


input_path <- commandArgs(TRUE)[1]
settings_file <- commandArgs(TRUE)[2]
#input_path <- paste("/var/www/sccr_project/scripts/", input_file, sep="")
#input_path <- '/var/www/sccr_project/scripts/ChIP_DerivedFiles.csv'
#settings_file <- '/var/www/sccr_project/secure/settings.txt'
derived_files <- read.delim(input_path, header=T, sep=",", as.is=T)
colnames(derived_files) <- c("exp_nid", "input1", "input2", "combined_name", "bigwig_file", "bed_file", "pdf_file", "log_file")
derived_rows <- dim(derived_files)[1]


# Load settings, reference files, global variables and connect to database
###############################################################################
# Read settings file 
data = read.table(settings_file, header=F)
dir_rlib = as.character(data[1,2])
dir_data = as.character(data[2,2])
dir_scripts = as.character(data[3,2])
database_user = as.character(data[4,2])
database_pass = as.character(data[5,2])
database_name = as.character(data[6,2])
database_host = as.character(data[7,2])
sparql_endpoint = as.character(data[8,2])
site_url = as.character(data[9,2])
alias_url = as.character(data[10,2])
RDF_reference_file = as.character(data[11,2])
isa_structure_file = as.character(data[12,2])
isa_translation_file = as.character(data[13,2])
ontology_reference_file = as.character(data[14,2])
drupal_path = as.character(data[15,2])
sparql_key = as.character(data[16,2])
server_path = as.character(data[17,2])

# Global Variables
job_id <- c(0)
exp_nid <- c(0)
method_name = "ChIP-Seq Analysis Pipeline 1"
method_id <- 25
chipseq_folder_drupal <- paste(drupal_path, "/chipseq/", sep = "")
chipseq_folder_path = paste(dir_data, "/chipseq/", sep = "")
exp_replicates <- data.frame(group_nid = integer(0), rep_id = integer(0), rep_name = character(0))

  
# Connect to database
library(RMySQL, lib.loc=dir_rlib)
m = dbDriver("MySQL")
con = dbConnect(m, username=database_user, password=database_pass, dbname=database_name, host=database_host)
rm(m)
on.exit(dbDisconnect(con))

# for each row of the input data frame
for (j in 1:derived_rows) { 
  exp_line = derived_files[j, "exp_nid"]
  
  if (exp_line != exp_nid) {
  
    # Update job status for previous line/experiment
    if (job_id > 0) {
      rs <- dbSendQuery(con, paste("UPDATE rtype_jobs SET status=1 WHERE job_id=", job_id, sep=""))
    }
    
    # Create a job for this experiment/analysis
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_jobs(job_id, job_type, exp_id, status, time_submitted) VALUES(NULL, 25, ", exp_line, ", 0, NOW())", sep=""))
    dbClearResult(rs) #if the result isn't cleared, the last insert id is 0
    job_id <- dbGetQuery(con, "select last_insert_id();")
    #job_id <- unlist(job_id)
    #cat("Created job_id: ", job_id, "\n")
    
    # Get replicates for this experiment so can match replicates to output files
    rs <- dbSendQuery(con, paste("select field_data_field_xf_replicate.entity_id as group_nid, field_data_field_xf_replicate_name.entity_id as rep_id, field_data_field_xf_replicate_name.field_xf_replicate_name_value as rep_name from field_data_field_xf_replicate_name left join field_data_field_xf_replicate on field_data_field_xf_replicate_name.entity_id = field_data_field_xf_replicate.field_xf_replicate_value left join field_data_field_xf_bioassay on field_data_field_xf_replicate.entity_id = field_data_field_xf_bioassay.field_xf_bioassay_target_id left join node on field_data_field_xf_bioassay.entity_id = node.nid where node.nid = ", exp_line, sep=""))
    exp_replicates <- fetch(rs, n=-1)
    cat("Got experiment replicate ids...\n")
    
    exp_nid <- exp_line
  }
  
  # match the replicate names to replicate ids
  input1_name <- derived_files[j, "input1"]
  input2_name <- derived_files[j, "input2"]
  input1_id <- exp_replicates[match(input1_name, exp_replicates[,"rep_name"]), "rep_id"]
  input2_id <- exp_replicates[match(input2_name, exp_replicates[,"rep_name"]), "rep_id"]
  cat("Line", j, " 1 ", input1_name, ":", input1_id, " 2 ", input2_name, ":", input2_id,"\n")
  
  #TODO: Make these functions? 
  # For each file entry:
  # 1. Test that file name exists, 2. URL encode file names, due to spaces and "+" in current standard
  # 3. Create drupal path   4. Insert into rtype_resultFiles   5. Insert into rtype_input   
  if (derived_files[j, "bigwig_file"] != "") {
    bigwig_file <- URLencode(derived_files[j, "bigwig_file"], reserved = TRUE)
    bigwig_drupal <- paste(chipseq_folder_drupal, exp_nid, "/", bigwig_file, sep = "")
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_resultFiles(job_id, file_path, file_type, method_id) VALUES(", job_id, ", '", bigwig_drupal,"', 'BIGWIG', ", method_id, ")", sep=""))
    dbClearResult(rs)
    bigwig_rfid <- dbGetQuery(con, "select last_insert_id();")
    
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_input(input_id, job_id, replicate_id, rf_id) VALUES(NULL, ", job_id, ", ", input1_id, ", ",bigwig_rfid, ")", sep=""))
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_input(input_id, job_id, replicate_id, rf_id) VALUES(NULL, ", job_id, ", ", input2_id, ", ",bigwig_rfid, ")", sep=""))
    #cat("Line", j, " input bigwig: ", bigwig_rfid, ":", bigwig_file, "\n")
  }
  
  if (derived_files[j, "bed_file"] != "") {
    bed_file <- URLencode(derived_files[j, "bed_file"], reserved = TRUE)
    bed_drupal <- paste(chipseq_folder_drupal, exp_nid, "/", bed_file, sep = "")
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_resultFiles(job_id, file_path, file_type, method_id) VALUES(", job_id, ", '", bed_drupal,"', 'BED', ", method_id, ")", sep=""))
    dbClearResult(rs)
    bed_rfid <- dbGetQuery(con, "select last_insert_id();")
    
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_input(input_id, job_id, replicate_id, rf_id) VALUES(NULL, ", job_id, ", ", input1_id, ", ",bed_rfid, ")", sep=""))
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_input(input_id, job_id, replicate_id, rf_id) VALUES(NULL, ", job_id, ", ", input2_id, ", ",bed_rfid, ")", sep=""))
  }
  
  if (derived_files[j, "pdf_file"] != "") {
    model_file <- URLencode(derived_files[j, "pdf_file"], reserved = TRUE)
    model_drupal <- paste(chipseq_folder_drupal, exp_nid, "/", model_file, sep = "")
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_resultFiles(job_id, file_path, file_type, method_id) VALUES(", job_id, ", '", model_drupal,"', 'MODEL_PDF', ", method_id, ")", sep=""))
    dbClearResult(rs)
    model_rfid <- dbGetQuery(con, "select last_insert_id();")
    
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_input(input_id, job_id, replicate_id, rf_id) VALUES(NULL, ", job_id, ", ", input1_id, ", ",model_rfid, ")", sep=""))
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_input(input_id, job_id, replicate_id, rf_id) VALUES(NULL, ", job_id, ", ", input2_id, ", ",model_rfid, ")", sep=""))
  }
  
  if (derived_files[j, "log_file"] != "") {
    log_file <- URLencode(derived_files[j, "log_file"], reserved = TRUE)
    log_drupal <- paste(chipseq_folder_drupal, exp_nid, "/", log_file, sep = "")
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_resultFiles(job_id, file_path, file_type, method_id) VALUES(", job_id, ", '", log_drupal,"', 'LOG', ", method_id, ")", sep=""))
    dbClearResult(rs)
    log_rfid <- dbGetQuery(con, "select last_insert_id();")
    
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_input(input_id, job_id, replicate_id, rf_id) VALUES(NULL, ", job_id, ", ", input1_id, ", ",log_rfid, ")", sep=""))
    rs <- dbSendQuery(con, paste("INSERT INTO rtype_input(input_id, job_id, replicate_id, rf_id) VALUES(NULL, ", job_id, ", ", input2_id, ", ",log_rfid, ")", sep=""))
  }
}

# Update status of very last job
rs <- dbSendQuery(con, paste("UPDATE rtype_jobs SET status=1 WHERE job_id=", job_id, sep=""))
